package fixturize

import (
	"fmt"
	"strings"
)

type SQLOptions struct {
	Transaction    bool
	OnConflictDN   bool
}

func (f *Fixture) ToSQL(opts SQLOptions) []byte {
	var b strings.Builder

	b.WriteString("-- Generated by fixturize (https://boringsql.com/products/fixturize/)\n")
	fmt.Fprintf(&b, "-- Root: %s\n", f.Meta.Root)
	fmt.Fprintf(&b, "-- Extracted at: %s\n", f.Meta.ExtractedAt.Format("2006-01-02T15:04:05Z"))

	if opts.Transaction {
		b.WriteString("\nBEGIN;\n")
	}

	order := f.TableOrder
	if len(order) == 0 {
		for name := range f.Tables {
			order = append(order, name)
		}
	}

	for _, tableName := range order {
		tbl, ok := f.Tables[tableName]
		if !ok || len(tbl.Rows) == 0 {
			continue
		}

		fmt.Fprintf(&b, "\n-- %s (%d rows)\n", tableName, len(tbl.Rows))
		fmt.Fprintf(&b, "INSERT INTO %s (%s)", QuoteQualifiedTable(tableName), QuoteColumns(tbl.Columns))

		if tbl.IdentityColumns {
			b.WriteString(" OVERRIDING SYSTEM VALUE")
		}

		b.WriteString("\nVALUES\n")

		for i, row := range tbl.Rows {
			b.WriteString("  (")
			for j, val := range row {
				if j > 0 {
					b.WriteString(", ")
				}
				b.WriteString(SQLLiteral(val))
			}
			b.WriteString(")")
			if i < len(tbl.Rows)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}

		if opts.OnConflictDN {
			b.WriteString("ON CONFLICT DO NOTHING")
		}

		b.WriteString(";\n")
	}

	if opts.Transaction {
		b.WriteString("\nCOMMIT;\n")
	}

	return []byte(b.String())
}

func SQLLiteral(val any) string {
	if val == nil {
		return "NULL"
	}

	switch v := val.(type) {
	case bool:
		if v {
			return "TRUE"
		}
		return "FALSE"
	case int:
		return fmt.Sprintf("%d", v)
	case int8:
		return fmt.Sprintf("%d", v)
	case int16:
		return fmt.Sprintf("%d", v)
	case int32:
		return fmt.Sprintf("%d", v)
	case int64:
		return fmt.Sprintf("%d", v)
	case float32:
		return fmt.Sprintf("%g", v)
	case float64:
		return fmt.Sprintf("%g", v)
	case string:
		if strings.HasPrefix(v, `\x`) {
			return "E'" + quoteStringLiteral(v) + "'"
		}
		return "'" + quoteStringLiteral(v) + "'"
	default:
		return "'" + quoteStringLiteral(fmt.Sprintf("%v", v)) + "'"
	}
}

func quoteStringLiteral(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
