package fixturize

import (
	"strings"
	"testing"
	"time"
)

func TestSQLLiteral(t *testing.T) {
	tests := []struct {
		name string
		val  any
		want string
	}{
		{"nil", nil, "NULL"},
		{"string", "hello", "'hello'"},
		{"string with quote", "it's", "'it''s'"},
		{"string with multiple quotes", "it's a 'test'", "'it''s a ''test'''"},
		{"empty string", "", "''"},
		{"bytea hex", `\x48656c6c6f`, `E'\x48656c6c6f'`},
		{"bytea hex with quote", `\x48'27`, `E'\x48''27'`},
		{"bool true", true, "TRUE"},
		{"bool false", false, "FALSE"},
		{"int", 42, "42"},
		{"int negative", -1, "-1"},
		{"int8", int8(8), "8"},
		{"int16", int16(16), "16"},
		{"int32", int32(32), "32"},
		{"int64", int64(64), "64"},
		{"float32", float32(3.14), "3.14"},
		{"float64", 2.718, "2.718"},
		{"float64 whole", float64(100), "100"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := SQLLiteral(tt.val)
			if got != tt.want {
				t.Errorf("SQLLiteral(%v) = %q, want %q", tt.val, got, tt.want)
			}
		})
	}
}

func newTestFixture() *Fixture {
	f := &Fixture{
		Meta: FixtureMeta{
			ExtractedAt: time.Date(2024, 1, 15, 10, 30, 0, 0, time.UTC),
			Root:        "organizations WHERE id = 42",
		},
		TableOrder: []string{"public.countries", "public.users"},
		Tables: map[string]*FixtureTable{
			"public.countries": {
				Columns: []string{"id", "name", "code"},
				Rows: [][]any{
					{int64(1), "United States", "US"},
					{int64(2), "Canada", "CA"},
				},
			},
			"public.users": {
				Columns: []string{"id", "name", "country_id"},
				Rows: [][]any{
					{int64(1), "Alice", int64(1)},
				},
			},
		},
	}
	return f
}

func TestToSQL(t *testing.T) {
	f := newTestFixture()
	got := string(f.ToSQL(SQLOptions{}))

	if !strings.Contains(got, "-- Generated by fixturize") {
		t.Error("missing header comment")
	}
	if !strings.Contains(got, "-- Root: organizations WHERE id = 42") {
		t.Error("missing root comment")
	}
	if !strings.Contains(got, "-- Extracted at: 2024-01-15T10:30:00Z") {
		t.Error("missing extracted_at comment")
	}

	// Verify ordering: countries before users
	countriesIdx := strings.Index(got, `"public"."countries"`)
	usersIdx := strings.Index(got, `"public"."users"`)
	if countriesIdx == -1 || usersIdx == -1 {
		t.Fatal("missing table INSERT statements")
	}
	if countriesIdx >= usersIdx {
		t.Error("countries should appear before users (table order)")
	}

	if !strings.Contains(got, "'United States'") {
		t.Error("missing row data")
	}
	if !strings.Contains(got, "-- public.countries (2 rows)") {
		t.Error("missing row count comment")
	}

	// No transaction wrapping by default
	if strings.Contains(got, "BEGIN") || strings.Contains(got, "COMMIT") {
		t.Error("should not contain transaction wrapping by default")
	}
}

func TestToSQLWithTransaction(t *testing.T) {
	f := newTestFixture()
	got := string(f.ToSQL(SQLOptions{Transaction: true}))

	if !strings.Contains(got, "\nBEGIN;\n") {
		t.Error("missing BEGIN")
	}
	if !strings.Contains(got, "\nCOMMIT;\n") {
		t.Error("missing COMMIT")
	}

	beginIdx := strings.Index(got, "BEGIN")
	commitIdx := strings.Index(got, "COMMIT")
	insertIdx := strings.Index(got, "INSERT")
	if beginIdx >= insertIdx || insertIdx >= commitIdx {
		t.Error("expected BEGIN before INSERT before COMMIT")
	}
}

func TestToSQLWithIdentity(t *testing.T) {
	f := &Fixture{
		Meta: FixtureMeta{
			ExtractedAt: time.Date(2024, 1, 15, 10, 30, 0, 0, time.UTC),
			Root:        "test",
		},
		TableOrder: []string{"public.audit_logs"},
		Tables: map[string]*FixtureTable{
			"public.audit_logs": {
				Columns:         []string{"id", "action"},
				Rows:            [][]any{{int64(1), "created"}},
				IdentityColumns: true,
			},
		},
	}
	got := string(f.ToSQL(SQLOptions{}))

	if !strings.Contains(got, "OVERRIDING SYSTEM VALUE") {
		t.Error("missing OVERRIDING SYSTEM VALUE for identity table")
	}
}

func TestToSQLWithOnConflict(t *testing.T) {
	f := newTestFixture()
	got := string(f.ToSQL(SQLOptions{OnConflictDN: true}))

	// Each table's INSERT should have ON CONFLICT DO NOTHING
	count := strings.Count(got, "ON CONFLICT DO NOTHING")
	if count != 2 {
		t.Errorf("expected 2 ON CONFLICT DO NOTHING clauses, got %d", count)
	}
}

func TestToSQLEmptyTable(t *testing.T) {
	f := &Fixture{
		Meta: FixtureMeta{
			ExtractedAt: time.Date(2024, 1, 15, 10, 30, 0, 0, time.UTC),
			Root:        "test",
		},
		TableOrder: []string{"public.empty", "public.nonempty"},
		Tables: map[string]*FixtureTable{
			"public.empty": {
				Columns: []string{"id"},
				Rows:    [][]any{},
			},
			"public.nonempty": {
				Columns: []string{"id"},
				Rows:    [][]any{{int64(1)}},
			},
		},
	}
	got := string(f.ToSQL(SQLOptions{}))

	if strings.Contains(got, "public.empty") {
		t.Error("empty table should be skipped")
	}
	if !strings.Contains(got, "public.nonempty") {
		t.Error("non-empty table should be present")
	}
}

func TestToSQLNullValues(t *testing.T) {
	f := &Fixture{
		Meta: FixtureMeta{
			ExtractedAt: time.Date(2024, 1, 15, 10, 30, 0, 0, time.UTC),
			Root:        "test",
		},
		TableOrder: []string{"public.items"},
		Tables: map[string]*FixtureTable{
			"public.items": {
				Columns: []string{"id", "name", "description"},
				Rows:    [][]any{{int64(1), "widget", nil}},
			},
		},
	}
	got := string(f.ToSQL(SQLOptions{}))

	if !strings.Contains(got, "NULL") {
		t.Error("nil value should produce NULL")
	}
	if !strings.Contains(got, "(1, 'widget', NULL)") {
		t.Errorf("unexpected row output, got: %s", got)
	}
}
